### ISSUE TITLE
Line Numbers missing with Mono

### ISSUE THREAD

**Issue by bitsandfoxes** [getsentry/sentry-unity#1053] opened 2022-10-27 15:13 UTC
Line numbers appear to be missing in events [Sample](https://sentry.io/organizations/sentry-sdks/issues/3300403573/events/a5f325ad230e4a1690eb294c8a9bd73b/?project=5439417)

The envelope that belong to the event:
```
{"sdk":{"name":"sentry.dotnet","version":"3.22.0"},"event_id":"a5f325ad230e4a1690eb294c8a9bd73b","sent_at":"2022-10-27T15:02:50.616284+00:00"}
{"type":"event","length":8182}
{"modules":
{"mscorlib":"4.0.0.0","UnityEngine":"0.0.0.0","UnityEngine.AIModule":"0.0.0.0","UnityEngine.ARModule":"0.0.0.0","UnityEngine.AccessibilityModule":"0.0.0.0","UnityEngine.AndroidJNIModule":"0.0.0.0","UnityEngine.AnimationModule":"0.0.0.0","UnityEngine.AssetBundleModule":"0.0.0.0","UnityEngine.AudioModule":"0.0.0.0","UnityEngine.ClothModule":"0.0.0.0","UnityEngine.ClusterInputModule":"0.0.0.0","UnityEngine.ClusterRendererModule":"0.0.0.0","UnityEngine.CoreModule":"0.0.0.0","UnityEngine.CrashReportingModule":"0.0.0.0","UnityEngine.DSPGraphModule":"0.0.0.0","UnityEngine.DirectorModule":"0.0.0.0","UnityEngine.GameCenterModule":"0.0.0.0","UnityEngine.GridModule":"0.0.0.0","UnityEngine.HotReloadModule":"0.0.0.0","UnityEngine.IMGUIModule":"0.0.0.0","UnityEngine.ImageConversionModule":"0.0.0.0","UnityEngine.InputModule":"0.0.0.0","UnityEngine.InputLegacyModule":"0.0.0.0","UnityEngine.JSONSerializeModule":"0.0.0.0","UnityEngine.LocalizationModule":"0.0.0.0","UnityEngine.ParticleSystemModule":"0.0.0.0","UnityEngine.PerformanceReportingModule":"0.0.0.0","UnityEngine.PhysicsModule":"0.0.0.0","UnityEngine.Physics2DModule":"0.0.0.0","UnityEngine.ProfilerModule":"0.0.0.0","UnityEngine.ScreenCaptureModule":"0.0.0.0","UnityEngine.SharedInternalsModule":"0.0.0.0","UnityEngine.SpriteMaskModule":"0.0.0.0","UnityEngine.SpriteShapeModule":"0.0.0.0","UnityEngine.StreamingModule":"0.0.0.0","UnityEngine.SubstanceModule":"0.0.0.0","UnityEngine.SubsystemsModule":"0.0.0.0","UnityEngine.TLSModule":"0.0.0.0","UnityEngine.TerrainModule":"0.0.0.0","UnityEngine.TerrainPhysicsModule":"0.0.0.0","UnityEngine.TextCoreModule":"0.0.0.0","UnityEngine.TextRenderingModule":"0.0.0.0","UnityEngine.TilemapModule":"0.0.0.0","UnityEngine.UIModule":"0.0.0.0","UnityEngine.UIElementsModule":"0.0.0.0","UnityEngine.UNETModule":"0.0.0.0","UnityEngine.UmbraModule":"0.0.0.0","UnityEngine.UnityAnalyticsModule":"0.0.0.0","UnityEngine.UnityConnectModule":"0.0.0.0","UnityEngine.UnityTestProtocolModule":"0.0.0.0","UnityEngine.UnityWebRequestModule":"0.0.0.0","UnityEngine.UnityWebRequestAssetBundleModule":"0.0.0.0","UnityEngine.UnityWebRequestAudioModule":"0.0.0.0","UnityEngine.UnityWebRequestTextureModule":"0.0.0.0","UnityEngine.UnityWebRequestWWWModule":"0.0.0.0","UnityEngine.VFXModule":"0.0.0.0","UnityEngine.VRModule":"0.0.0.0","UnityEngine.VehiclesModule":"0.0.0.0","UnityEngine.VideoModule":"0.0.0.0","UnityEngine.WindModule":"0.0.0.0","UnityEngine.XRModule":"0.0.0.0","System.Core":"4.0.0.0","System":"4.0.0.0","Assembly-CSharp":"0.0.0.0","UnityEngine.UI":"1.0.0.0","io.sentry.unity.dev.runtime":"0.0.0.0","System.Reflection.Metadata":"5.0.0.0","Sentry.Unity.iOS":"0.24.0.0","System.Text.Encodings.Web":"5.0.0.1","System.Text.Json":"5.0.0.0","System.Threading.Tasks.Extensions":"4.2.0.1","Sentry":"3.22.0.0","System.Buffers":"4.0.3.0","Sentry.Unity":"0.24.0.0","System.Runtime.CompilerServices.Unsafe":"5.0.0.0","System.Numerics.Vectors":"4.1.4.0","System.Collections.Immutable":"5.0.0.0","System.Memory":"4.0.1.1","Microsoft.Bcl.AsyncInterfaces":"5.0.0.0","netstandard":"2.0.0.0","System.Net.Http":"4.0.0.0","Mono.Security":"4.0.0.0"},"event_id":"a5f325ad230e4a1690eb294c8a9bd73b","timestamp":"2022-10-27T15:02:50.492079+00:00","platform":"csharp","release":"unity-of-bugs@0.1\u002Bafddca9df7e7343f598128efa19e028c","exception":
{"values":[
    {"type":"System.InvalidOperationException","value":"Exception from a lady beetle \uD83D\uDC1E","module":"mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089","thread_id":1,"stacktrace":
{"frames":[
    {"function":"Execute","module":"UnityEngine.EventSystems.ExecuteEvents","in_app":false,"package":"UnityEngine.UI, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null","instruction_offset":99},
{"function":"Execute","module":"UnityEngine.EventSystems.ExecuteEvents","in_app":false,"package":"UnityEngine.UI, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null","instruction_offset":7},
{"function":"OnPointerClick","module":"UnityEngine.UI.Button","in_app":false,"package":"UnityEngine.UI, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null","instruction_offset":9},
{"function":"Press","module":"UnityEngine.UI.Button","in_app":false,"package":"UnityEngine.UI, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null","instruction_offset":28},
{"function":"Invoke","module":"UnityEngine.Events.UnityEvent","in_app":false,"package":"UnityEngine.CoreModule, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null","instruction_offset":34},
{"function":"Invoke","module":"UnityEngine.Events.InvokableCall","in_app":false,"package":"UnityEngine.CoreModule, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null","instruction_offset":16},
{"function":"StackTraceExampleA","module":"BugFarmButtons","in_app":true,"package":"Assembly-CSharp, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null","instruction_offset":0},
{"function":"StackTraceExampleB","module":"BugFarmButtons","in_app":true,"package":"Assembly-CSharp, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null","instruction_offset":0}]},"mechanism":
{"type":"Unity.LogException","handled":false}}]},"level":"error","request":
{},"contexts":
{"device":
{"type":"device","timezone":"Local","name":"Bitfox","model":"MacBookPro18,3","battery_level":100,"memory_size":34359738368,"boot_time":"2022-10-21T23:35:29.1025103+00:00","processor_count":10,"cpu_description":"Apple M1 Pro","device_type":"Desktop","battery_status":"Full","supports_vibration":false},"runtime":
{"type":"runtime","name":"Mono","version":"5.11.0","raw_description":"Mono 5.11.0 ((HEAD/5c72e251312)"},"ThreadPool Info":
{"min_worker_threads":10,"min_completion_port_threads":10,"max_worker_threads":1000,"max_completion_port_threads":200,"available_worker_threads":1000,"available_completion_port_threads":200},"Current Culture":
{"name":"en-US","display_name":"English (United States)","calendar":"GregorianCalendar"},"app":
{"type":"app","app_start_time":"2022-10-27T15:02:22.005969+00:00","build_type":"release"},"gpu":
{"type":"gpu","name":"Apple M1 Pro","id":0,"vendor_id":"0","vendor_name":"Apple","memory_size":21845,"api_type":"Metal","multi_threaded_rendering":true,"version":"Metal","npot_support":"Full","max_texture_size":16384,"graphics_shader_level":"Shader Model 5.0","supports_draw_call_instancing":true,"supports_ray_tracing":false,"supports_compute_shaders":true,"supports_geometry_shaders":false},"unity":
{"type":"unity","install_mode":"Unknown","copy_texture_support":"Basic, Copy3D, DifferentTypes, TextureToRT, RTToTexture","rendering_threading_mode":"MultiThreaded","target_frame_rate":"-1"},"os":
{"type":"os","raw_description":"Mac OS X 10.16.0"}},"user":
{},"environment":"production","sdk":
{"packages":[
    {"name":"upm:sentry.unity","version":"0.24.0"},
{"name":"nuget:sentry.dotnet","version":"3.22.0"}],"name":"sentry.dotnet.unity","version":"0.24.0"},"breadcrumbs":[
    {"timestamp":"2022-10-27T15:02:22.789Z","message":"BeforeSceneLoad","category":"scene.beforeload"},
{"timestamp":"2022-10-27T15:02:22.863Z","message":"Changed active scene to \u0027\u0027","category":"scene.changed"},
{"timestamp":"2022-10-27T15:02:24.881Z","message":"Scene \u0027\u0027 was unloaded","category":"scene.unloaded"},
{"timestamp":"2022-10-27T15:02:24.958Z","message":"Changed active scene to \u00271_Bugfarm\u0027","category":"scene.changed"},
{"timestamp":"2022-10-27T15:02:24.958Z","message":"Scene \u00271_Bugfarm\u0027 was loaded","category":"scene.loaded"},
{"timestamp":"2022-10-27T15:02:24.974Z","message":"Sample Start \uD83E\uDD8B","category":"unity.logger"},
{"timestamp":"2022-10-27T15:02:24.974Z","message":"Here come the bugs \uD83D\uDC1E\uD83E\uDD8B\uD83D\uDC1B\uD83D\uDC1C\uD83D\uDD77!","category":"unity.logger","level":"warning"},
{"timestamp":"2022-10-27T15:02:26.529Z","message":"Ending Sentry Session","type":"session","category":"app.lifecycle"},
{"timestamp":"2022-10-27T15:02:26.656Z","message":"System.NullReferenceException: Object reference not set to an instance of an object.","category":"unity.logger","level":"error"}],"tags":
{"unity.install_mode":"Unknown","unity.gpu.supports_instancing":"true","unity.device.device_type":"Desktop","unity.is_main_thread":"true"}}
```

**Comment by Swatinem** [comment] 2022-10-31 08:02
This is a .NET stack trace, with `instruction_offset`. So this requires .NET symbolication, and not C++/IL2CPP.

https://github.com/getsentry/sentry-dotnet/pull/1785 would eventually solve this.

**Comment by vaind** [comment] 2022-10-31 13:15
is this not a duplicate of #884 ?

**Comment by bitsandfoxes** [comment] 2022-10-31 14:44
> is this not a duplicate of #884 ?

This one is about C# exceptions. #884 is about native crashes.

**Closed** 2022-12-14 13:06 UTC
Labels: Bug, Platform: Unity
