### ISSUE TITLE
Line Numbers Not Showing for Mobile Exceptions (Android & some iOS)

### ISSUE THREAD

**Issue by cstavitsky** [getsentry/sentry-unity#1673] opened 2024-05-30 22:20 UTC
Opening this issue on behalf of a trialing Sentry customer. Bug Report may not be quite accurate but we aren't clear as to why line numbers aren't showing for Unity exceptions captured by Sentry on Android (and some on iOS), and are looking for help troubleshooting.

### Environment

How do you use Sentry?
Sentry SaaS (sentry.io)

Which version of the SDK?

```
sentry.dotnet.unity
--
Version | 2.0.1+318ab00a2245007aba0d09b24cbf39dc6daabafd
```

How did you install the package? (Git-URL, Assetstore)
Git-URL

Which version of Unity?
`2021.3.19f1`

Is this happening in Unity (editor) or on a player like Android, iOS, Windows?
Android/iOS

### Steps to Reproduce

Triggered errors in Unity mobile game in iOS and Android.

- They confirmed that they are using IL2CPP, which should make this [IL2CPP Line Numbers documentation](https://docs.sentry.io/platforms/unity/configuration/il2cpp/) relevant.- The customer has uploaded debug symbols for their Android project
    -  ([Per the docs](https://docs.sentry.io/platforms/unity/configuration/il2cpp/) on IL2CPP Line Numbers, “The support for line numbers in C# Exceptions with IL2CPP relies on the debug symbol upload. With the automated debug symbol upload enabled, the [Sentry SDK will upload the line mapping automatically](https://docs.sentry.io/platforms/unity/native-support/#debug-symbols).”)
    - Link to Debug symbols, project, etc included in internal customer case, also attached in associated Jira ticket -- reach out to @cstavitsky on Slack if you have trouble finding these
- ([Per the docs](https://docs.sentry.io/platforms/unity/configuration/il2cpp/) on IL2CPP Line Numbers, line numbers should be enabled by default: “This feature is enabled by default. You can opt out of it through the editor configuration window by selecting Tools -> Sentry -> Advanced -> IL2CPP line numbers or [programmatically](https://docs.sentry.io/platforms/unity/configuration/options/#programmatic-configuration).”)
    -  Based on this, I asked the team to confirm their editor configuration and they provided this screenshot. My understanding is that IL2CPP line numbers are enabled correctly since the box is checked:

![image (80)](https://github.com/getsentry/sentry-unity/assets/12092849/7a1a1193-3171-4ed5-b035-268d20ebaca6)

- Here is their Sentry config, which looks normal to me:
<img width="1173" alt="Screenshot 2024-05-30 at 3 11 45 PM" src="https://github.com/getsentry/sentry-unity/assets/12092849/774e0a3b-301b-454d-b9e0-393aeeda925e">

### Expected Result

Line numbers would be associated for exceptions triggered in both Android and iOS.

### Actual Result

Line numbers are not associated.

### Additional Context

> we tried to rebuild several times and test with the apk, there was line numbers. We also tested the APK that come with current Live build and it worked, however it didn't work with the play store version (that we assume it come from the .aab build)
> 
> We just try to submit the new build (tested with apk version) and will test it when it available on internal beta play store to confirm it.
> 
> - our live build will output both apk file and aab file.
> - we submit the aab file to google play store
> - the current live build download from doesn't show the line numbers
> - BUT when we test with the apk file from first step, it has the line numbers displayed.
> 
> So we assume that there is something different with apk and aab build. We just submitted a new beta build to confirm it again tomorrow.

after they tried that, they wrote:

> On the Sentry Dashboard, the number of lines of code is always shown when we use an APK file to install for testing. However, no number of lines of code is displayed when we install our game from the Google Play Store. The number of lines of code is normally shown on iOS. [settings are shown in the images below. under Steps to Reproduce]

- Full context and event links, project, etc included in internal customer case, also attached in associated Jira ticket -- reach out to @cstavitsky on Slack if you have trouble finding these

#### Android Example with no line numbers
<img width="1210" alt="Screenshot 2024-05-30 at 3 21 20 PM" src="https://github.com/getsentry/sentry-unity/assets/12092849/12070254-9f6d-4a3b-9418-ac0c3fd53eac">

#### iOS Example with no line numbers
<img width="1204" alt="Screenshot 2024-05-30 at 3 22 08 PM" src="https://github.com/getsentry/sentry-unity/assets/12092849/71244c47-eb4f-44fd-be17-23594b84804a">

┆Issue is synchronized with this [Jira Improvement](https://getsentry.atlassian.net/browse/FEEDBACK-2188) by [Unito](https://www.unito.io)

**Comment by bitsandfoxes** [comment] 2024-06-05 14:43
Just to make sure this isn't it, we have a know limitation regarding line numbers documented [here](https://docs.sentry.io/platforms/unity/troubleshooting/known-limitations/#stack-traces).
But based on the stacktrace in the screenshots this ain't the issue here.

**Comment by bitsandfoxes** [comment] 2024-06-05 14:44
One thing I noticed on the stacktraces of these issues: Both of them seem to originate from plugins. Do those plugins provide debug symbols as part of their packages? Are they just `.cs` scripts?

**Comment by bitsandfoxes** [comment] 2024-06-05 14:45
Some links to those issues would be greatly appreciated.

**Comment by cstavitsky** [comment] 2024-06-05 16:49
> I'm having trouble summarizing this as there seem to be a couple of issues in one. On Android:
> 
> 1. Line numbers work in regular builds/dev-builds when outputting an APK and running that on a device
> 2. Line numbers **do not** work when uploading to the google playstore as an aab

@bitsandfoxes thanks for taking a look! Today our customer sent this additional context:

> We have more context about the issue:
> - We use the following command to distribute the AAB file:
> 
> ```
> gradle bundleRelease -b build.gradle
> ```
> 
> - We have tried installing the AAB file on a device and got the following results:
> 
> **Line of code is shown in the case of:**
> 
> 1. Installing using the adb tool from a MacOS machine with bundleTool and mode=universal:
> 
> ```
> java -jar ~/bundletool/bundletool.jar build-apks --bundle=/path/to/your_app.aab --output=/path/to/output.apks --mode=universal
> ```
> 
>   2.  Uploading the AAB file to Microsoft AppCenter, then downloading and installing it. Note that in AppCenter’s documentation it is mentioned:
> `"When you distribute Android Application Bundle (AAB), App Center generates a universal APK, signs it with a generated signing key, and distributes it to a device."` Source: [link](https://learn.microsoft.com/en-us/appcenter/distribution/uploading)
> 
> **The line of code is NOT shown in the case of:**
> - Installing from Google beta/Google Play Store
> 
> There is a difference between installing the app from Google and manually installing using Mode Universal. When installing from Google, the AAB itself will be split into smaller APKs as defined in the build.gradle, for example: base-master.apk, base-arm64_v8a.apk, base-armeabi_v7a.apk.
> For some reason, the symbol files uploaded to Sentry do not work fully with this method. Below is the list of symbol files uploaded with the build.
> 
> ![sentry_symbol1](https://github.com/getsentry/sentry-unity/assets/12092849/6aec711f-e6a2-4828-ac92-05fc98a5c7d7)
> 
> ![sentry_symbol2](https://github.com/getsentry/sentry-unity/assets/12092849/6ee9f875-c959-403d-8643-c6529d8306ad)
> 
> From the early days of implementing Sentry, we found that if we only use the “Upload Dev Symbols” and “Upload Sources” options in the Symbols tab of Sentry Unity Tools, the line of code is not displayed even with the APK file. Therefore, we used this command to upload the Symbols after building the app:
> ```
> export SENTRY_PROPERTIES=./sentry.properties && ./sentry-cli-Darwin-universal debug-files upload --include-sources --il2cpp-mapping [project-path]
> ```
> We noticed that using the above command results in a more complete upload of symbol files, and the line of code is displayed for the APK file. So, we are currently continuing to use this method of uploading.
> 
> ![image (82)](https://github.com/getsentry/sentry-unity/assets/12092849/f328e1de-5c7c-4492-93a5-6ccd0ea2be62)
> 
> <img width="683" alt="sentryconfig" src="https://github.com/getsentry/sentry-unity/assets/12092849/5c39c32f-1c39-4e7f-b97a-615126177369">

That concludes their additional context. To address your other questions:

> On iOS - it never works? It doesn't work in a released build out of the app store?

This I will need to clarify with the customer. They came asking about the problem primarily with Android (and while poking around I noticed that some line numbers are also missing). So from their perspective, the original problem is primarily the Android one, I just surfaced what I thought might be a relevant problem.

> Just to make sure this isn't it, we have a know limitation regarding line numbers documented [here](https://docs.sentry.io/platforms/unity/troubleshooting/known-limitations/#stack-traces). But based on the stacktrace in the screenshots this ain't the issue here.

I will also need to confirm this with the customer. I'll also encourage them to reply directly here to you to save time!

> One thing I noticed on the stacktraces of these issues: Both of them seem to originate from plugins. Do those plugins provide debug symbols as part of their packages? Are they just .cs scripts?

I will encourage the customer to follow up about this as well.

> Some links to those issues would be greatly appreciated.

Links to these issues are here in the [internal customer case](https://www.notion.so/sentry/Unity-project-not-showing-line-numbers-for-exceptions-captured-on-Android-9da097bcea5a4b23aff5b05e7f4e1fff?pvs=4#dc6c66cd2dad44b1ad3d5508b6ca57c9).

**Comment by phuongdt88** [comment] 2024-06-06 10:44
@bitsandfoxes 
As we can see currently, line numbers are displayed for the iOS production build, except for some cases:

- Async methods
- IEnumerator
- UniRx.Async.UniTask.Run

We will retry these cases with **StackTraceMode.Enhanced**.

Currently, we are focusing on the issue of line numbers not displaying for the **Android** production build (installed with the **aab** file). And this issue simply comes from the .cs files.

**Comment by bitsandfoxes** [comment] 2024-06-06 15:01
Thanks for the additional feedback.
We'd definitely expect those to work for async methods and coroutines. I think we even have samples for those. We'll check up on that.

Issues with UniRx seem familiar to Cysharp's UniTask which is a known limitation.
At the time of an exception, the SDK requests the instruction address from Unity's IL2CPP backend. When originating from UniRx and UniTask Unity always returns addresses as `0x0`.

**Comment by bitsandfoxes** [comment] 2024-06-10 17:11
@hunglvgearinc, definitely!

**Comment by bitsandfoxes** [comment] 2024-06-17 10:26
As an update and since we're rolling this up from the Android side:
I'm testing this with Unity `2021.3.38f1` and checking for error events with their line numbers intact:
- APK: works
- AAB: works
So this is working locally, which leads me to believe that something is going on on the Google Play Store side of things.

**Comment by smeubank** [comment] 2024-07-02 12:11
I am re-opening this issue for the time being to correctly reflect feedback for at least one customer, and we need to budget time to investigate

**Comment by bitsandfoxes** [comment] 2024-07-05 12:02
I've submitted and setup our own sample via the Google Play Console to be able to fully test this. I need to wait for us to pass the review to be able to download the sample via the playstore. Directly downloading the apk from the dashboard seems to be no different than a local dev-build.
I'll update here once I know more.

**Comment by bitsandfoxes** [comment] 2024-07-10 14:21
I'm failing to reproduce the missing line numbers in builds downloaded from the Play Store.

**Comment by bitsandfoxes** [comment] 2024-12-11 14:24
Closing this as I'm failing to reproduce the issue. Any type of repro would be highly appreciated.

**Closed by bitsandfoxes** 2024-12-11 14:24 UTC
Labels: Bug, Sync: Jira
