### ISSUE TITLE
Exception on Sentry Native Bridge 

### ISSUE THREAD

**Issue by eomene** [getsentry/sentry-unity#1085] opened 2022-11-18 13:40 UTC
### Environment

How do you use Sentry?
Sentry SaaS ([sentry.io](http://sentry.io/)) or self-hosted/on-premise (which version?)
Sentry SaaS ([sentry.io](http://sentry.io/))

Which version of the SDK?
0.26.0
How did you install the package? (Git-URL, Assetstore)
Git-url

Which version of Unity?
2021.3.10

Is this happening in Unity (editor) or on a player like Android, iOS, Windows?
Seems to happen on all platforms

### Steps to Reproduce
Build a Unity project with sentry included

### Expected Result
We should not get any exception from sentry

### Actual Result
We constantly get this exception on our dashboard.

System.Exception Sentry.Unity.Native.SentryNativeBridge in Init
Sentry native-error capture configuration failed to load a native library. This usually means the library is missing from the application bundle
What actually happened. Maybe a screenshot/recording? Maybe some logs?

### Any logs or screenshots
```
System.Exception
Sentry native-error capture configuration failed to load a native library. This usually means the library is missing from the application bundle or the installation directory.
System.DllNotFoundException
Unable to load DLL 'sentry'. Tried the load the following dynamic libraries: Unable to load dynamic library 'sentry' because of 'Failed to open the requested dynamic library (0x06000000) - 找不到指定的模块。  (WinError:0000007e)

Sentry.Unity.Native.SentryNativeBridge in Init at line 491

Sentry.Unity.Native.SentryNativeBridge in Init at line 3502

Sentry.Unity.Native.SentryNativeBridge in Init at line 3005

Sentry.Unity.Native.SentryNative in Configure at line 2581

Sentry.Unity.SentryInitialization in Init at line 72
```
TYPE
CATEGORY
DESCRIPTION
LEVEL
TIME
scene.beforeload
BeforeSceneLoad
Info
13:22:15
exception
System.DllNotFoundException: Unable to load DLL 'sentry'. Tried the load the following dynamic libraries: Unable to load dynamic library 'sentry' because of 'Failed to open the requested dynamic library (0x06000000) - 找不到指定的模块。  (WinError:0000007e)

**Comment by bitsandfoxes** [comment] 2022-11-18 18:14
Thanks for letting us know. I'll look into this.

**Comment by bitsandfoxes** [comment] 2022-11-23 09:18
I don't seem to be able to reproduce this issue.
Do you let the SDK self-initialize? Do you make use of the programmatic `configure` functionality?
Would you be able to create a repro you could share with us?

**Comment by eomene** [comment] 2022-11-24 12:44
Hi. We let the sdk self initialise, we do use the configure via scriptable object and also update it at some point in the game. We cant really make a repo reproducing it. but it shows up in our project often. The data I added came directly from sentry. its actually a bit weird that sentry reports to us that sentry dlls could not be loaded.  And we did find this https://forum.unity.com/threads/dll-cannot-be-loaded-but-it-is-right-there-next-to-the-executable.1305945/ not sure if its related

**Comment by vaind** [comment] 2022-11-24 15:33
@eomene looks like an issue with a missing dependency (CRT). Can you share more details from the issue so that we can see the platform, OS version, etc?

**Comment by eomene** [comment] 2022-11-24 15:38
Maybe this can help 
![image](https://user-images.githubusercontent.com/16381081/203821988-71e31473-84d4-45cc-9d52-562edb952c52.png)

**Comment by eomene** [comment] 2022-11-24 15:39
Maybe this can help
![image](https://user-images.githubusercontent.com/16381081/203822202-a93d7ade-3f94-4fd9-90f2-6672cf5b819e.png)

**Comment by bitsandfoxes** [comment] 2023-05-23 15:17
Hey, sorry for the long silence. Does this issue still persist for you? There have been quite a few changes.

**Comment by bitsandfoxes** [comment] 2023-06-20 14:50
Closing this due to old age and me being unable to reproduce. Please, feel free to reopen this issue if it persists.

**Closed by bitsandfoxes** 2023-06-20 14:50 UTC
Labels: Bug, Platform: Unity

**Comment by Webee-JC** [comment] 2024-05-07 14:25
Still persist though..
![image](https://github.com/getsentry/sentry-unity/assets/65617985/5e38a028-acf5-4ffc-ad65-421703a1806d)

**Comment by Webee-JC** [comment] 2024-05-07 14:26
![image](https://github.com/getsentry/sentry-unity/assets/65617985/9df3d224-02d5-4f9a-a61f-d8e5eb5244de)

**Comment by Webee-JC** [comment] 2024-05-07 14:27
Happens in sentry version 2.0.4

**Comment by Webee-JC** [comment] 2024-05-10 09:50
Hey @bitsandfoxes 
Yes, ok. I'll try to create a new one for it.

PS
Sorry for the late reply. So busy.

**Comment by PoisonousJohn** [comment] 2024-06-05 07:55
Could you please share a link to the new issue? We see the same error

**Comment by bitsandfoxes** [comment] 2024-06-05 14:29
https://github.com/getsentry/sentry-unity/issues/1647
