### ISSUE TITLE
Sentry: (Error) SentryEvent processing failed. UnityEngine.UnityException: get_isDebugBuild can only be called from the main thread.

### ISSUE THREAD

**Issue by ArnauKokoro** [getsentry/sentry-unity#277] opened 2021-08-11 14:47 UTC
### Environment

How do you use Sentry?
Sentry SaaS

Which SDK and version?
Unity@0.4.3

Platform?
Mac M1 Unity Editor with iOS Platform selected

### Steps to Reproduce

1. Install Sentry package and configure it
2. Run Application on Mac M1 Unity Editor using iOS platform

### Expected Result

No errors thrown on startup

### Actual Result

It logs an error:

`Sentry: (Error) SentryEvent processing failed. UnityEngine.UnityException: get_isDebugBuild can only be called from the main thread.`

**Comment by bruno-garcia** [comment] 2021-08-11 14:54
The bug report is for the Sentry SDK for .NET version 1.2.0? This one? https://www.nuget.org/packages/Sentry/1.2.0

Since then we shipped a new SDK (Sentry.Unity) that's being built in this repo. We have docs for it here: https://docs.sentry.io/platforms/unity/

Could you give that a try and let us know if the problem goes away?

**Comment by ArnauKokoro** [comment] 2021-08-11 14:57
@bruno-garcia Sorry, my fault. I'm using Unity package 0.4.3

**Comment by ArnauKokoro** [comment] 2021-08-13 10:09
@bruno-garcia is there any solution for this? Is causing Unity Editor freeze and we had to remove the package to keep working.

Many Thanks!!

**Comment by bitsandfoxes** [comment] 2021-08-17 12:04
Hey, @ArnauKokoro! Which version of Unity are you using? I can't seem to be able to reproduce it.
On the plus side we've already merged https://github.com/getsentry/sentry-unity/pull/268 and just waiting to be released. It should take care of this very issue (us grabbing stuff from non main threads).

**Comment by ArnauKokoro** [comment] 2021-08-17 15:00
Hi @bitsandfoxes! We are using 2020.3.13f1. We can reproduce it closing the editor and opening it again.

Thanks, we will keep on track.

**Comment by bitsandfoxes** [comment] 2021-08-17 15:55
Hi, a follow-up! As a temporary workaround, you could disable `Capture in Editor`. The fix for this comes with the next release.
![Screenshot 2021-08-17 at 17 52 14](https://user-images.githubusercontent.com/25725783/129759265-c35dddf3-635e-4a13-8fcc-0613059ca058.png)

**Comment by bitsandfoxes** [comment] 2021-08-24 11:19
Hi @ArnauKokoro! We just released 0.5.0 today that contains the fix for this issue. I would very much appreciate it if you could give it a try!

**Closed as completed** 2021-08-25 21:10 UTC
Labels: Bug

**Comment by ArnauKokoro** [comment] 2021-09-03 09:16
Hi guys!! Just try it with 0.5.1 version and now it never starts the scene clicking on play button on the editor, it stuck loading and never plays. I tried also without Capture Editor check.

Thanks.

**Comment by ArnauKokoro** [comment] 2021-09-04 15:04
My fault, it was not Sentry. It works perfect!!

Thanks!!

**Comment by bruno-garcia** [comment] 2021-09-09 22:47
That's great news. Thanks @ArnauKokoro for trying and giving feedback 🙏
