### ISSUE TITLE
Sentry.Unity.Editor.iOS and AppDomain.CurrentDomain.GetAssemblies() for Android target platform

### ISSUE THREAD

**Issue by PeraDllGD** [getsentry/sentry-unity#525] opened 2022-01-20 15:45 UTC
### Environment

Which version of the SDK?
0.9.3 (imported with package manager)

Which version of Unity?
2019.4.16f1

Is this happening in Unity (editor) or on a player like Android, iOS, Windows?
Happening only in Editor

### Steps to Reproduce

After implementing Sentry problem appeared with custom inspector drawing. One of assets we are using is Lip Sync Pro and when you select game object with lipsync pro script on it (or eye controller script), its not drawing things properly (throwing exception). 
After debugging we found that when its looping through AppDomain.CurrentDomain.GetAssemblies(), and GetTypes() is called for each assembly, its throwing exception and main culprit is Sentry.Unity.Editor.iOS.dll which if is deleted, no exception is thrown. 

Our target platform is Android, so this dll should be excluded from assemblies. 

(temporal solution we found is to update code on multiple places to make it work - with try/catch - some of other assets are using same approach - but this is just for preventing consequences)

**Comment by bitsandfoxes** [comment] 2022-01-21 13:00
Thanks @PeraDllGD, for raising this. We just recently changed the import settings for `Sentry.Unity.Editor.iOS.dll` and we are aware that this might lead to issues on some of the older Unity versions (we tested it on 2019.4.33f1 and newer).
Do you have the Unity iOS module installed? Are you on Windows or on macOS?

**Comment by PeraDllGD** [comment] 2022-01-21 15:35
Thanks for reply. Its on Windows, and I don't have iOS module installed for this Unity version, so probably it wasn't able to find it and changed to default one which triggered problem.

**Comment by bitsandfoxes** [comment] 2022-01-24 10:28
I see that you're on a pretty old Unity version as well. I'm closing this since it a Unity update or iOS module installation will fix it.
Please let us know if you're running into any issues.

**Comment by PeraDllGD** [comment] 2022-01-24 11:45
Just tried with latest 2019 LTS version (34f1) and problem is still there, and as iOS module is not required for development purpose, do you think its safe deleting that file? Maybe in future update we can have option what to include and what not depending on target platform. Thanks in advance

**Comment by bitsandfoxes** [comment] 2022-01-24 14:51
Yes, if you don't require the iOS build t target then you can just remove the `Sentry.Unity.Editor.iOS.dll`.
We'll take another look. Could you provide us with your `YourProject/Packages/manifest.json` file? I'd like to be able to reproduce this issue.

**Comment by PeraDllGD** [comment] 2022-01-24 17:11
Hopefully I got your email right, I sent you email titled **Issue #525**

**Comment by bitsandfoxes** [comment] 2022-01-26 14:56
You can reach me at stefan@sentry.io

**Comment by bitsandfoxes** [comment] 2022-01-28 16:34
Thanks for sharing the project with us @PeraDllGD. I could not reproduce the issue even with 2019.4.16f1 but I know I should so there is definitely something going on.

**Comment by PeraDllGD** [comment] 2022-01-28 23:32
Try with clean new 2019 Unity installation without any module installed (doesn't need to be latest LTS), as this is happening on all coworkers Unity-s, also we are all using win 10 (as you might use other OS)

**Comment by bitsandfoxes** [comment] 2022-01-31 13:07
Do you happen to have a stacktrace for us?

**Comment by PeraDllGD** [comment] 2022-01-31 14:55
ReflectionTypeLoadException: Exception of type 'System.Reflection.ReflectionTypeLoadException' was thrown.
System.Reflection.Assembly.GetTypes () (at <9577ac7a62ef43179789031239ba8798>:0)
RogoDigital.Lipsync.AutoSync.AutoSyncUtility.GetModuleTypes () (at Assets/Rogo Digital/LipSync Pro/AutoSync/Editor/AutoSyncUtility.cs:102)
RogoDigital.Lipsync.AutoSyncSetupWizard.OnEnable () (at Assets/Rogo Digital/LipSync Pro/Editor/AutoSyncSetupWizard.cs:63)
UnityEditor.EditorWindow:GetWindow(Boolean)
RogoDigital.Lipsync.AutoSyncSetupWizard:ShowWindow() (at Assets/Rogo Digital/LipSync Pro/Editor/AutoSyncSetupWizard.cs:216)

(one example, when you open from menu items - Window -> Robo Digital -> LipSync Pro -> AuthSync Setup Wizard)
its always the same, any plugin that didn't include try/catch for GetTypes() (and used reflection approach) will throw exception

**Comment by foriequal0** [comment] 2022-02-06 09:04
We're experiencing the same problem with Unity `2020.3.19f1` on Windows (without iOS module).
Same exception but different locations.

**Comment by PeraDllGD** [comment] 2022-02-06 10:19
Here is our solution (not the best one, but it works for us for now)
(put script **SentryDLLFixer** in **Editor folder**)

using System.Collections.Generic;
using System.Linq;
using System.IO;

using UnityEngine;
using UnityEditor;

[InitializeOnLoad]
public static class SentryDLLFixer
{
    static SentryDLLFixer()
    {
        var metaPath = "Library/PackageCache";
        if (!Directory.Exists(metaPath))
        {
            Debug.Log($"Could not find path: {metaPath}");
            return;
        }

        var sentryFolderName = Directory.GetDirectories(metaPath, "io.sentry.unity@*").FirstOrDefault();
        if (string.IsNullOrEmpty(sentryFolderName))
        {
            Debug.Log($"Could not find sentry folder under [{metaPath}]");
            return;
        }

        metaPath = Path.Combine(sentryFolderName, "Editor/iOS/Sentry.Unity.Editor.iOS.dll.meta");
        if (!File.Exists(metaPath))
        {
            Debug.Log($"Could not find file: {metaPath}");
            return;
        }

        var metaContent = File.ReadAllLines(metaPath).ToList();
        var numLines = metaContent.Count;
        var iLine = 0;
        while (iLine < numLines && !metaContent[iLine++].EndsWith("Editor: Editor"))
        {
            continue;
        }
        while (iLine < numLines && !metaContent[iLine++].EndsWith("settings:"))
        {
            continue;
        }
        var settings = new Dictionary<string, string>();
        while (iLine < numLines && !metaContent[iLine].Trim().StartsWith("-"))
        {
            var keyvar = metaContent[iLine++].Trim().Split(':');
            if (keyvar[0].Trim() == "OS")
            {
                metaContent.RemoveAt(--iLine);
            }
            settings[keyvar[0].Trim()] = keyvar[1].Trim();
        }
        if (!settings.ContainsKey("OS") || settings["OS"] != "OSX")
        {
            metaContent.Insert(iLine, "        OS: OSX");
            File.WriteAllLines(metaPath, metaContent);
            AssetDatabase.Refresh(ImportAssetOptions.ForceUpdate);
        }
    }
}

**Comment by foriequal0** [comment] 2022-02-06 13:21
I've fixed this by putting this script into Editor folder.
```
using UnityEditor;

public sealed class SentryIOSBuildSupportFixer : AssetPostprocessor
{
    private static readonly bool IsIOSBuildTargetSupportLoaded = IsBuildTargetSupportLoaded(BuildTarget.iOS);

    public void OnPreprocessAsset()
    {
        if (IsIOSBuildTargetSupportLoaded)
        {
            return;
        }

        if (!assetPath.Contains("Sentry.Unity.Editor.iOS.dll"))
        {
            return;
        }

        var pluginImporter = (PluginImporter) assetImporter;
        pluginImporter.SetExcludeEditorFromAnyPlatform(true);
        pluginImporter.SetCompatibleWithEditor(false);
    }

    private static bool IsBuildTargetSupportLoaded(BuildTarget buildTarget)
    {
        var moduleManager = System.Type.GetType("UnityEditor.Modules.ModuleManager,UnityEditor.dll");
        var isPlatformSupportLoaded = moduleManager.GetMethod("IsPlatformSupportLoaded", System.Reflection.BindingFlags.Static | System.Reflection.BindingFlags.NonPublic);
        var getTargetStringFromBuildTarget = moduleManager.GetMethod("GetTargetStringFromBuildTarget", System.Reflection.BindingFlags.Static | System.Reflection.BindingFlags.NonPublic);
        var targetString = (string)getTargetStringFromBuildTarget.Invoke(null, new object[] { buildTarget });
        return (bool)isPlatformSupportLoaded.Invoke(null,new object[] { targetString });
    }
}
```

**Comment by bitsandfoxes** [comment] 2022-02-07 15:58
Thanks a lot for sharing your solutions. I'd love to add them to the SDK. Unfortunately, they require the SDK to be either loaded from disk or the package to be embedded in the project for the import settings to be able to be manipulated.
Sorry for the inconvenience.

**Closed** 2022-02-14 18:32 UTC
Labels: Bug, Editor, Effort: Small, Impact: Small, Platform: Unity

**Comment by bruno-garcia** [comment] 2022-02-14 21:50
Should be resolved on: https://github.com/getsentry/sentry-unity/releases/tag/0.10.0
