### ISSUE TITLE
Unity libil2cpp.so increased from 83mb to 103mb in unity android

### ISSUE THREAD

**Issue by Nkwenom** [getsentry/sentry-unity#1582] opened 2024-03-09 08:06 UTC
### Environment

How do you use Sentry?
Sentry Saas

Which version of the SDK?
2.0.0

How did you install the package? (Git-URL, Assetstore)
git-url

Which version of Unity?
2021.3.16f1

Is this happening in Unity (editor) or on a player like Android, iOS, Windows?
Android build

### Steps to Reproduce
Make an Android Build

### Expected Result
build size slightly larger than without SentrySDK (~5mb).
Build without Sentry (aab) - 218mb

### Actual Result
Build with SentrySDK (aab) - 230mb

### Any logs or screenshots
We have use .net standart 2.1.
I saw this issue https://github.com/getsentry/sentry-unity/issues/1113, but there is no solution there.
![image](https://github.com/getsentry/sentry-unity/assets/35425640/1220dc03-1fad-4c16-9dc3-60bf4644b4e6)
![image](https://github.com/getsentry/sentry-unity/assets/35425640/87d8e72f-0a88-44ff-b522-6f54264e48c9)

**Comment by bitsandfoxes** [comment] 2024-03-11 21:33
Hey @Nkwenom, thanks for reaching out.
I think we can take another look at where the MB go.

**Comment by bitsandfoxes** [comment] 2024-04-05 14:46
Closing this as duplicate of https://github.com/getsentry/sentry-unity/issues/1113

**Closed by bitsandfoxes** 2024-04-05 14:46 UTC
Labels: Repository Maintenance
