### ISSUE TITLE
Add LowMemory notification to breadcrumbs

### ISSUE THREAD

**Issue by vaind** [getsentry/sentry-unity#757] opened 2022-05-23 07:22 UTC
Maybe it would be helpful to diagnose some events if you could see that previously a low-memory notification came (https://docs.unity3d.com/ScriptReference/Application-lowMemory.html). 

* we could add this automatically to breadcrumbs. If we're doing so, we should ensure we only add it once (or once for a given period of time).
* alternatively, we could just remember this in the event processor and set the extra info of the last low-memory event time when an error occurs - this wouldn't work for native though, and that's probably where this is most useful.

**Comment by vaind** [comment] 2022-05-31 15:46
Let's have a look at how it's done on sentry-cocoa/java (breadcrumb or event)

**Comment by bitsandfoxes** [comment] 2024-12-12 19:46
Duplicate of https://github.com/getsentry/sentry-unity/issues/93

**Closed by bitsandfoxes** 2024-12-12 19:46 UTC
Labels: Feature
