### ISSUE TITLE
Facebook SDK: System.Collections.Immutable.dll reflection changes

### ISSUE THREAD

**Issue by liproman** [getsentry/sentry-unity#22] opened 2019-04-26 16:03 UTC
Hi, when I use sentrySDK from feature branch and add System.Collections.Immutable.dll to project/ After this my other libraries throw exceprions to console. 
For example we can use FB SDK ( 7.13 or 7.15 ) and if I start application this sdk can throw exception to console : ReflectionTypeLoadException: Exception of type 'System.Reflection.ReflectionTypeLoadException' was thrown. 
I try some variants and setting - only System.Collections.Immutable.dll broke normal application work =(
I use API Compability Level : .NET Stardart 2.0 in project ( but 4.x version have the same errors ) 
Is you can solve this problem ?

**Comment by bruno-garcia** [comment] 2019-05-03 08:40
@liproman would it be possible to provide a reproducible project so we can debug through?
We haven't tested Facebook SDK support yet so I'm unaware of the constraints it has.
AOT environments (like iOS) introduce some limitations with regards to reflection so this is something that we'll need to investigate further.

**Comment by bruno-garcia** [comment] 2020-09-30 01:54
One update: The .NET SDK has dropped all dependencies other than Newtonsoft.Json.
When we get to push that as the new SDK, this issue should be gone.

**Comment by bruno-garcia** [comment] 2020-11-05 00:04
Just reading this again:

This isn't about the `sentry.unit.lite` SDK that this repository contains but the experimental on top of Sentry .NET, is that correct?

Did you add all `.dll`s that the .NET SDK require to work into Unity? Your error message says it couldn't find one of those.

**Comment by bruno-garcia** [comment] 2020-11-05 00:05
Removed the `bug` tag since this is about the branch experiment. 

Please provide a repro so we can help you out.

**Comment by bruno-garcia** [comment] 2020-12-22 23:24
The code in the `main` branch doesn't depend on this type anymore. Closing.

**Closed by bruno-garcia** 2020-12-22 23:24 UTC
