### ISSUE TITLE
Add deobfuscation support

### ISSUE THREAD

**Issue by rodolfoBee** [getsentry/sentry-unity#1769] opened 2024-08-19 09:33 UTC
Which version of the SDK?
It happens on both v2.1.3 and v1.8.0

The deployed code is being obfuscated but Sentry is not showing the deobfuscated function names in the stack trace, even when the necessary DIFs are available in the project. 

Reproduction project is available on the internal shadow ticket.

### Expected Result
The resulting stack trace in Sentry shows the deobfuscated function names.

### Actual Result
Function names in stack trace are obfuscated.

┆Issue is synchronized with this [Jira Improvement](https://getsentry.atlassian.net/browse/FEEDBACK-2257) by [Unito](https://www.unito.io)

**Comment by tustanivsky** [comment] 2024-08-20 07:21
Hey @rodolfoBee, here's an update regarding this issue:

It looks that the reproduction project uses this [Unity plugin](https://assetstore.unity.com/packages/tools/utilities/obfuscator-free-89420) which essentially performs game code obfuscation when targeting Windows platform.

Even though there are DIFs available captured events' callstack can't be properly deobfuscated and symbolicated without a corresponding [mapping file](https://guardingpearsoftware.com/docs/obfuscator/windows/stacktrace-deobfuscation/) that the plugin should generate if configured.

There's also an editor utility provided along with the above plugin that allows viewing deobfuscated error stack traces after specifying the mapping file path and pasting the obfuscated code manually but is supposed to work on the client only.

Currently, Sentry Unity SDK doesn't upload any third-party mappings along with other debug symbols by default and what's more important those won't be picked up automatically on the server side of things to deobfuscate error callstack unless Sentry supports such integration.

cc @bitsandfoxes

**Comment by bitsandfoxes** [comment] 2024-08-26 10:56
Currently, Sentry does not offer support for deobfuscation for anything but ProGuard/R8 and DexGuard.
That'd be an entirely new feature on Sentry itself.
I'm keeping that issue open to gauge interest.

**Comment by bruno-garcia** [comment] 2024-10-12 15:34
This is a duplicate of:
* https://github.com/getsentry/sentry-unity/issues/689

**Closed** 2024-10-12 15:34 UTC
Labels: Feature, Sync: Jira
