### ISSUE TITLE
(Warning) Push scope called in global mode, returning. 

### ISSUE THREAD

**Issue by ripperdoc** [getsentry/sentry-unity#446] opened 2021-12-06 10:26 UTC
### Environment

How do you use Sentry?
Sentry SaaS (sentry.io)

Which SDK and version?
Sentry Unity 0.6.2

### Steps to Reproduce

If I follow the example in docs for local scope with attachments I get a warning, and the message doesn't make it clear what I need to change. The example:
```
// Local Scope
SentrySdk.WithScope(scope =>
{
    scope.AddAttachment("log.txt");

    SentrySdk.CaptureMessage("my message");
});
```

### Expected Result

No warning.

### Actual Result

I get a warning:
```
Sentry: (Warning) Push scope called in global mode, returning. 
UnityEngine.Debug:LogWarning (object)
Sentry.Unity.UnityLogger:Log (Sentry.SentryLevel,string,System.Exception,object[]) (at /Users/runner/work/sentry-unity/sentry-unity/src/Sentry.Unity/UnityLogger.cs:44)
Sentry.Extensibility.DiagnosticLoggerExtensions:LogIfEnabled (Sentry.Extensibility.IDiagnosticLogger,Sentry.SentryLevel,System.Exception,string)
Sentry.Extensibility.DiagnosticLoggerExtensions:LogWarning (Sentry.SentryOptions,string)
Sentry.Internal.SentryScopeManager:PushScope<object> (object)
Sentry.Internal.SentryScopeManager:PushScope ()
Sentry.Internal.SentryScopeManager:WithScope (System.Action`1<Sentry.Scope>)
Sentry.Internal.Hub:WithScope (System.Action`1<Sentry.Scope>)
Sentry.SentrySdk:WithScope (System.Action`1<Sentry.Scope>)
SettingsPopup/<>c:<Awake>b__31_6 () (at Assets/Scripts/UI/SettingsPopup.cs:78)
UnityEngine.XR.Interaction.Toolkit.UI.UIInputModule:Update () (at Library/PackageCache/com.unity.xr.interaction.toolkit@1.0.0-pre.8/Runtime/UI/UIInputModule.cs:109)
```

**Comment by bitsandfoxes** [comment] 2021-12-06 18:40
Hey @ripperdoc, thanks for raising this. We'll look into it in conjunction with #448

**Comment by bruno-garcia** [comment] 2021-12-07 12:44
The alternative API is tracked here:

* https://github.com/getsentry/sentry-dotnet/issues/675

**Comment by bruno-garcia** [comment] 2022-01-11 19:36
Closing this as we removed the WithScope API from docs and this PR (https://github.com/getsentry/sentry-dotnet/pull/1412) will introduce an alternative API. The warning is by design.

**Closed by bruno-garcia** 2022-01-11 19:36 UTC
Labels: Bug
