### ISSUE TITLE
System.Exception   Sentry.Unity.Native.SentryNativeBridge in Init

### ISSUE THREAD

**Issue by Webee-JC** [getsentry/sentry-unity#1647] opened 2024-05-10 13:37 UTC
### Environment

How do you use Sentry?
Sentry SaaS (sentry.io) or self-hosted/on-premise (which version?)

Which version of the SDK?
![image](https://github.com/getsentry/sentry-unity/assets/65617985/d25ec062-4562-4ac9-9c70-15c36acd3e3e)

How did you install the package? (Git-URL, Assetstore)
Git-URL

Which version of Unity?
2021.3.37f1

Is this happening in Unity (editor) or on a player like Android, iOS, Windows?
Window or Standalone

### Steps to Reproduce

1. Just install and setup the sentry.
2. I don't know if it's related but the error `Sentry.Unity.ApplicationNotResponding` comes along with it. That's why I disabled ANR because we're not supporting background process or so I assumed.

### Expected Result

No errors in the logs.

### Actual Result

It shows the said error.

### Any logs or screenshots
![image](https://github.com/getsentry/sentry-unity/assets/65617985/3dcfa457-3571-4cce-b306-9e1c30d208df)
![image](https://github.com/getsentry/sentry-unity/assets/65617985/3d1329d9-8711-43fa-9ec3-5f39714f755d)
![image](https://github.com/getsentry/sentry-unity/assets/65617985/218a4445-091d-44e0-84c9-78006cb0e9d2)

**Comment by bitsandfoxes** [comment] 2024-05-13 08:20
Hey @Webee-JC, thanks for raising this. Could you share what your build-output looks like? Maybe `tree` the output path?
Specifically, I'm looking for `sentry-native`. It should be at `OutputPath/Your_Project_Name_Data/Plugins/x86_64/sentry.dll`.

**Comment by bitsandfoxes** [comment] 2024-06-21 08:43
Closing this as duplicate of https://github.com/getsentry/sentry-unity/issues/1440

**Closed by bitsandfoxes** 2024-06-21 08:43 UTC
Labels: Bug, Windows
