### ISSUE TITLE
Event confirming event submission

### ISSUE THREAD

**Issue by ripperdoc** [getsentry/sentry-unity#776] opened 2022-06-02 09:27 UTC
What problem could Sentry solve that it doesn't?

Many times in production we've had issues with Sentry events not submitting as expected. It has been many different reasons. Many of them have been our errors in code that runs when an event is created or sent (eg event processors, attachments, beforeSend). Sometimes it's been user networking issues or Sentry outages.

What I would wish for is a simple event that I could listen to that confirms that an event has been received. I could use this to display feedback to a user after an error report or that an error was caught and reported. I currently do this in beforeSend, but that's a bit fake as it might very well fail to send after beforeSend has run. Even better if this or a related event could also trigger if Sentry knows that something went wrong during sending, so that I can handle that case in the UI (e.g. ask the user to send report again or do some additional logging).

**Comment by bitsandfoxes** [comment] 2022-06-02 13:19
Hey @ripperdoc. I'm not sure this can be done easily. For example: While Sentry acknowledges to the SDK to have received an event, that event could then get dropped by Relay (for whatever reason) and not show up on the issues page. And Relay dropping an event is not getting communicated back to the SDK.

What I could think of as an alternative solution to your BeforeSend workaround is adding your own [BackgroundWorker](https://github.com/getsentry/sentry-dotnet/blob/88a6be4d1457a5befaa5419996798dc7ea94060b/src/Sentry/Extensibility/IBackgroundWorker.cs) that takes care of actually sending the event.
 Similar to what we do for WebGL and "unknown platforms" here: https://github.com/getsentry/sentry-unity/blob/main/src/Sentry.Unity/UnityWebRequestTransport.cs

We might have to take another look at the `Configure` callback because we're overriding the BackgroundWorker, especially in those cases but would that work for you in general

**Comment by bruno-garcia** [comment] 2022-06-07 15:09
Relates to: https://github.com/getsentry/sentry-javascript/issues/2939

**Comment by ripperdoc** [comment] 2022-06-08 07:59
I understand it's hard to guarantee delivery status, but I'd be happy with getting at least the same information that is routed to the debug log anyway, e.g. there I would see if an event was delivered or not.

I can look into BackgroundWorker, I am using the one you just released for WebGL (after previously using a similar but hackier way of sending when on WebGL), but I am concerned of creating bugs or losing future improvements by not using your BackgroundWorker.

**Comment by bitsandfoxes** [comment] 2024-12-11 12:56
As stated in the linked issues, this unfortunately is a `won't fix`. The transport is fire and forget by design.

**Closed by bitsandfoxes** 2024-12-11 12:56 UTC
Labels: Feature
