### ISSUE TITLE
A locked main thread for 5 seconds does not send an ANR report to sentry

### ISSUE THREAD

**Issue by oddgames-david** [getsentry/sentry-unity#493] opened 2021-12-22 04:59 UTC
### Environment

How do you use Sentry?
Sentry SaaS

Which SDK and version?
0.9.1

### Steps to Reproduce

Lock the main thread doing:
while(true) { }
tap the screen

### Expected Result

After a 6 seconds expect a sentry issue to be sent from the android sdk

### Actual Result

Nothing happens

**Comment by bitsandfoxes** [comment] 2021-12-22 13:15
Correct me if I'm wrong but as far as I know Unity creates and lives in its own thread and never actually blocks the Android main thread. So if you were to experience an ANR error in a Unity game it's most likely due to a native plugin.

**Comment by oddgames-david** [comment] 2021-12-24 00:55
@bitsandfoxes Loading screens triggering an ANR wouldn't be a false positive, that'd be something to fix by spreading out the load.

**Comment by oddgames-david** [comment] 2021-12-24 01:39
The reason I wanted to do a test is because I've put out my app with Sentry to 10% of my users and the play store is capturing ANR's but my sentry project doesn't show any.

**Comment by oddgames-david** [comment] 2021-12-24 05:50
This code keeps my game's graphics running but all input will now be blocked and after 5 seconds android os will tell me the game is frozen and if I want to wait or crash the game but there is no ANR report in sentry for it.

```
AndroidJavaClass unityPlayer = new AndroidJavaClass("com.unity3d.player.UnityPlayer");
AndroidJavaObject activity = unityPlayer.GetStatic<AndroidJavaObject>("currentActivity");
activity.Call("runOnUiThread", new AndroidJavaRunnable(() => { while (true) { } }));
```

**Comment by oddgames-david** [comment] 2022-01-07 01:24
@bitsandfoxes Do you have test code to simulate an ANR so I can test that sentry is actually able to receive ANR data? I've got many ANR's on my google dashboard but 0 in my sentry one.

**Comment by bitsandfoxes** [comment] 2022-01-10 10:31
> ```
> AndroidJavaClass unityPlayer = new AndroidJavaClass("com.unity3d.player.UnityPlayer");
> AndroidJavaObject activity = unityPlayer.GetStatic<AndroidJavaObject>("currentActivity");
> activity.Call("runOnUiThread", new AndroidJavaRunnable(() => { while (true) { } }));
> ```

Your snippet works for me and leads to an ANR on Sentry that looks like this:

![Screenshot 2022-01-10 at 11 13 05](https://user-images.githubusercontent.com/25725783/148749316-4024a161-abde-44a7-a13c-19c5f615db1b.png)

Additionally, you should see some info logs: 
```
2022/01/10 11:23:38.030 17438 22754 Info Sentry Raising ANR
2022/01/10 11:23:38.031 17438 22754 Info Sentry ANR triggered with message: Application Not Responding for at least 5000 ms.
```

Is the SDK self-initializing?

**Comment by oddgames-david** [comment] 2022-01-10 11:34
My test was not using self initialization. I guess without programmatic init I won't have ANR so I'll have to wait.
Get Outlook for Android

**Comment by bitsandfoxes** [comment] 2022-01-10 16:25
What functionality are you missing from the self-initialization approach? Maybe we can get that sooner out of the way than the full programmatic support for native.

**Comment by oddgames-david** [comment] 2022-01-11 11:07
> What functionality are you missing from the self-initialization approach? Maybe we can get that sooner out of the way than the full programmatic support for native.

Exception filters but more specifically: Only using error logs as breadcrumbs (don't send them to the server). Exceptions still send as usual.

**Comment by bruno-garcia** [comment] 2022-01-11 20:00
If I understand this, it's a dupe of #511 with support for adding hooks such as beforeSend and other things. Feel free to reopen otherwise.

**Closed by bruno-garcia** 2022-01-11 20:00 UTC
Labels: Enhancement
