### ISSUE TITLE
Crash on Android 5 devices after some seconds

### ISSUE THREAD

**Issue by Awais6** [getsentry/sentry-unity#1211] opened 2023-03-03 00:00 UTC
### Environment

How do you use Sentry?
Sentry SaaS (sentry.io) or self-hosted/on-premise (which version?) sentry.io

Which version of the SDK?
0.28.1 and 1.0.0 both have same error both tested

How did you install the package? (Git-URL, Assetstore)
git url

Which version of Unity?
2020.3.44f1 LTS

Is this happening in Unity (editor) or on a player like Android, iOS, Windows?
Confirmed Android 5.0 Devices and maybe Android 6.0 too

### Steps to Reproduce

I have Google Admob + Firebase + Facebook + Photon + Sentry SDKs in the game. I removed all the SDKs one by one to find the buggy SDK, at last when I just turn off the sentry SDK app then started running smoothly. I have retested it twice with the clean build, there is some bug in Sentry SDK. It is 100% confirmed it crashes on an android 5.0 device.

### Expected Result

should not crash

### Actual Result

It shows in the Android Logcat:
![image](https://user-images.githubusercontent.com/46025225/222594059-28b32df2-d2e3-44b1-9e36-1d40f78546de.png)

**Comment by Awais6** [comment] 2023-03-03 00:11
moreover, I am using SentryOptionsConfiguration

```
public override void Configure(SentryUnityOptions options)
    {
        // Your code here
        options.BeforeSend = BeforeSend;
        // options.DisableAnrIntegration();
    }

    private static SentryEvent BeforeSend(SentryEvent arg)
    {
        arg.SetTag("IsSignedIn", FireAuth.IsSignedInAndReady.ToString());
        arg.SetTag("UId", FirestoreData.SharedDocument?.userId ?? "No Id");
        arg.SetTag("Scene", SceneManager.GetActiveScene().name);
        return arg;
    }
```

**Comment by bitsandfoxes** [comment] 2023-03-03 15:22
Thanks for raising this! I'll take a look!

**Comment by bitsandfoxes** [comment] 2023-03-06 11:48
To isolate the cause: Can you reproduce this with native support in `Tools -> Sentry -> Advanced -> Android Native Support` disabled?

**Comment by bitsandfoxes** [comment] 2023-03-07 16:15
Hey, could you provide us with additional logcat logs? I'm very keen on taking a look at this.
Since you were already testing this extensively, could you share a repro with us?
Thanks!

**Comment by vic910** [comment] 2023-03-15 09:47
i have same program in android 5.crash log is 
03-15 10:50:01.005 W/art     ( 8652): Native thread exiting without having called DetachCurrentThread (maybe it's going to use a pthread_key_create destructor?): Thread[31,tid=9108,Native,Thread*=0xee8aec00,peer=0x130d20a0,"Thread-7617"]

03-15 10:50:01.005 F/art     ( 8652): art/runtime/thread.cc:1082] Native thread exited without calling DetachCurrentThread: Thread[31,tid=9108,Native,Thread*=0xee8aec00,peer=0x130d20a0,"Thread-7617"]

**Comment by vic910** [comment] 2023-03-15 09:51
i have same program in android 5.crash log is 
03-15 10:50:01.005 W/art     ( 8652): Native thread exiting without having called DetachCurrentThread (maybe it's going to use a pthread_key_create destructor?): Thread[31,tid=9108,Native,Thread*=0xee8aec00,peer=0x130d20a0,"Thread-7617"]

03-15 10:50:01.005 F/art     ( 8652): art/runtime/thread.cc:1082] Native thread exited without calling DetachCurrentThread: Thread[31,tid=9108,Native,Thread*=0xee8aec00,peer=0x130d20a0,"Thread-7617"]

**Comment by vic910** [comment] 2023-03-16 02:35
set Android Native Support disabled  is OK

**Comment by vic910** [comment] 2023-03-16 03:44
how disable sentry in android 5 at runtime

**Comment by bitsandfoxes** [comment] 2023-03-17 10:48
> how disable sentry in android 5 at runtime

You can disable Sentry at runtime with the [`RuntimeConfiguration`](https://docs.sentry.io/platforms/unity/configuration/options/#programmatic-configuration). You can try checking for the Android version there and set `options.Enabled = false;`. This prevents the SDK from initializing and shuts down the Android SDK.

**Comment by NicoWakatoon** [comment] 2023-08-28 15:15
@bitsandfoxes I have the same problem on an Android 6 device, how can I help you to debug this issue ? 
```
W/art: Native thread exiting without having called DetachCurrentThread (maybe it's going to use a pthread_key_create destructor?): Thread[23,tid=17273,Native,Thread*=0xca660000,peer=0x134220a0,"Thread-3924"]
A/art: art/runtime/thread.cc:1238] Native thread exited without calling DetachCurrentThread: Thread[23,tid=17273,Native,Thread*=0xca660000,peer=0x134220a0,"Thread-3924"]
A/art: art/runtime/runtime.cc:368] Runtime aborting...
A/art: art/runtime/runtime.cc:368] 
```

I exported the project to android studio to catch the exception. in the native debugger here is the stacktrace: 


<img width="1177" alt="Screenshot 2023-08-28 at 17 15 01" src="https://github.com/getsentry/sentry-unity/assets/133665865/66387d9e-ab46-4da9-8a11-4962793d874a">



Disabling Sentry at runtime on Android device <= 6 seem to fix the issue, but i'd like to be able to to catch problems old devices too.

**Comment by bitsandfoxes** [comment] 2023-08-29 09:38
Hey, thanks for the helping hand! Is this only happening on a physical device? Does this happen in the emulator too?

**Comment by NicoWakatoon** [comment] 2023-08-29 12:04
Hi I have not tried on the emulator. if it'm important I can try it but I need to rebuilt everything to support X86 emulator

**Comment by NicoWakatoon** [comment] 2023-08-31 08:38
Same problem using the x86 emulator ( Nexus 4 API 23 )  :
```
W/art: Native thread exiting without having called DetachCurrentThread (maybe it's going to use a pthread_key_create destructor?): Thread[22,tid=7690,Native,Thread*=0x904f3000,peer=0x12f1c0a0,"Thread-225"]
A/art: art/runtime/thread.cc:1223] Native thread exited without calling DetachCurrentThread: Thread[22,tid=7690,Native,Thread*=0x904f3000,peer=0x12f1c0a0,"Thread-225"]
I/sentry-native: entering signal handler
D/sentry-native: captured backtrace with 11 frames
D/sentry-native: merging scope into event
D/sentry-native: trying to read modules from /proc/self/maps
D/sentry-native: read 124 modules from /proc/self/maps
D/sentry-native: adding attachments to envelope
D/sentry-native: sending envelope
D/sentry-native: serializing envelope into buffer
I/sentry-native: crash has been captured
    
    --------- beginning of crash
A/libc: Fatal signal 11 (SIGSEGV), code 1, fault addr 0x9c in tid 7690 (Thread-225)
Disconnected from the target VM, address: 'localhost:64606', transport: 'socket'
```

**Comment by bitsandfoxes** [comment] 2023-09-04 15:53
Thanks for confirming this. I'll see what I can find out.

**Comment by packedbox** [comment] 2023-11-10 22:02
@bitsandfoxes any update on this issue ?

**Comment by bitsandfoxes** [comment] 2023-11-13 17:16
Unfortunately, nothing definitive. What we do have now is more granular control over what gets initialized and you can selectively disable the NDK only while keeping the rest of the Android Native support.

**Comment by bitsandfoxes** [comment] 2024-05-14 13:56
Thanks for all the input so far and apologies for the slow progress. We can finally reproduce this and have a lead as to how to resolve it. 
I'm closing this in favor of: https://github.com/getsentry/sentry-unity/issues/1591

**Closed by bitsandfoxes** 2024-05-14 13:56 UTC
Labels: Bug, Android
